#!/usr/bin/env python
import sys
import os

import argparse

from algorithm_test_runner import collect_suite_classes


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="Algorithm test runner")
    args = parser.parse_args(sys.argv[1:])

    suite_classes = collect_suite_classes(os.getcwd())
    print('\n'.join(c.__name__ for c in suite_classes))
