#!/usr/bin/env python
import sys
import os

from algorithm_test_runner.runner import suite_name_to_class_map, initialize_stores
from algorithm_test_runner.util import print_error


def parse_arguments(arguments):
    suite = None
    case = None
    result = None
    flags = {}
    for arg in arguments:
        if arg in ['-h', '--help']:
            flags['help'] = True
        elif suite is None:
            suite = arg
        elif case is None:
            case = arg
        elif result is None:
            result = arg
        else:
            raise ValueError('Too many arguments')
    return suite, case, result, flags


def print_usage():
    print('\n'.join([
        'usage:',
        '  algtr [SUITE [CASE]]',
        '  algtr SUITE CASE RUN view',
    ]))


if __name__ == '__main__':
    try:
        suite_name, case_name, result_identifier, flags = parse_arguments(sys.argv[1:])
    except ValueError:
        print_error('Incorrect usage')
        print_usage()
        sys.exit(1)

    if 'help' in flags:
        print_usage()
        sys.exit(0)


    working_directory = os.getcwd()
    suite_map = suite_name_to_class_map(working_directory)
    stores = initialize_stores(working_directory)

    if suite_name is None:
        # TODO: execute all
        print('\n'.join(suite_map))
        sys.exit(0)

    if suite_name in suite_map:
        suite = suite_map[suite_name]()
        print('\n'.join(suite.case_map))
    else:
        print_error('Unknown suite name "{}"'.format(suite_name))
        sys.exit(1)
