#!/usr/bin/env python
import sys

import scipy.io
import affine


if __name__ == '__main__':
    if len(sys.argv) != 4:
        print('Usage: applyaffine TRANSFORM POINTS OUTPUTPOINTS')
        sys.exit(1)

    transform_mat_filename = sys.argv[1]
    registration_matrix = scipy.io.loadmat(transform_mat_filename)['registration_matrix']

    A_xyz_mat_filename = sys.argv[2]
    A = scipy.io.loadmat(A_xyz_mat_filename)['points']

    A_registered = affine.apply_affine(registration_matrix, A)

    output_mat_filename = sys.argv[3]
    scipy.io.savemat(output_mat_filename, {
        'points': A_registered,
    })
