#!/usr/bin/env python
import sys

import scipy.io
import numpy as np

import points


if __name__ == '__main__':
    if len(sys.argv) != 3:
        print('Usage: averageclumps POINTS CLUMPEDPOINTS')
        sys.exit(1)

    input_mat_filename = sys.argv[1]
    raw_points = scipy.io.loadmat(input_mat_filename)['points']

    max_distance_to_neighbors_mm = 3.0
    sets_of_clumped_indices = points.segment(raw_points, max_distance_to_neighbors_mm)

    clumped_points = np.empty((3, len(sets_of_clumped_indices)), dtype=float)
    for i, indices_to_clump in enumerate(sets_of_clumped_indices):
        points_to_clump = raw_points[:, np.array([i for i in indices_to_clump])]
        clumped_points[:, i] = np.average(points_to_clump, axis=1)

    output_mat_filename = sys.argv[2]
    scipy.io.savemat(output_mat_filename, {
        'points': clumped_points,
    })
