#!/bin/bash

set -e

source .env
database_name=$(echo $DATABASE_URL | grep -Eo '[a-z_-]+$')
if ! psql $DATABASE_URL -c 'SELECT 1;' > /dev/null 2>&1 ; then
    createdb "$database_name"
    python server/manage.py migrate
    python server/manage.py generate_demo_data
else
    echo "Database \"$database_name\" already exists!"
fi
