#!/usr/bin/env python
#
# Script to convert a CSV file with three columns (x, y, z) of points
# into a mat file with x, y, z numpy arrays
import argparse

import scipy.io
import numpy as np


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('csvfile', help='Input path to read csv-file')
    parser.add_argument('matfile', help='Output path to write mat-file')
    args = parser.parse_args()

    points = np.genfromtxt(args.csvfile)
    scipy.io.savemat(args.matfile, {
        'points': points.T,
    })
