#!/usr/bin/env python
import argparse

import scipy.io

from feature_detection import FeatureDetector


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('voxels', help='Input path to read voxels mat-file')
    parser.add_argument('points', help='Output path to write points mat-file')
    args = parser.parse_args()

    voxel_data = scipy.io.loadmat(args.voxels)
    voxels = voxel_data['voxels']
    ijk_to_xyz = voxel_data['ijk_to_patient_xyz_transform']
    phantom_name = voxel_data['phantom_name'][0]

    points_in_patient_xyz = FeatureDetector(phantom_name, voxels, ijk_to_xyz).run()

    scipy.io.savemat(args.points, {'points': points_in_patient_xyz})
