#!/usr/bin/env python
import sys

import dicom
import scipy.io

from dicom_import import combine_slices


if __name__ == '__main__':
    if len(sys.argv) <= 3:
        print('Usage: dicom2mat DICOMFILES... MATFILE')
        sys.exit(1)

    input_dicom_filenames = sys.argv[1:-1]
    dicom_datasets = [dicom.read_file(f) for f in input_dicom_filenames]

    voxels, irc_to_patient_xyz_transform = combine_slices(dicom_datasets)

    output_mat_filename = sys.argv[-1]
    scipy.io.savemat(output_mat_filename, {
        'voxels': voxels,
        'ijk_to_patient_xyz_transform': irc_to_patient_xyz_transform,
    })
