#!/usr/bin/env python
import argparse

import scipy.io

from dicom_import import combined_series_from_zip


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('zip', help='Zip archive containing DICOM files from a series')
    parser.add_argument('voxels', help='Output path to write voxels mat-file')
    args = parser.parse_args()

    voxels, irc_to_patient_xyz_transform = combined_series_from_zip(args.zip)

    scipy.io.savemat(args.voxels, {
        'voxels': voxels,
        'ijk_to_patient_xyz_transform': irc_to_patient_xyz_transform,
    })
