version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: cirs
      POSTGRES_PASSWORD: cirs_password
      POSTGRES_DB: cirs
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "cirs"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - my_network

  client:
    image: node:7.8
    working_dir: /app
    volumes:
      - .:/app
    environment:
      DEBUG: 1
      BASE_URL: http://distortioncheck:8000
      PORT: 8000
      REDIS_URL: redis://
    command: >
      sh -c "rm -f /usr/local/bin/yarn /usr/local/bin/yarnpkg &&
             npm install -g yarn &&
             yarn &&
             yarn build:dev"
    healthcheck:
      test: ["CMD", "sh", "-c", "test -f /app/requirements.txt"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - my_network

  backend:
    image: python:3.9
    working_dir: /app
    hostname: distortioncheck
    volumes:
        - .:/app
    environment:
      DATABASE_URL: postgres://cirs:cirs_password@postgres/cirs
      DEBUG: 1
      BASE_URL: http://localhost:8000
      PORT: 8000
      REDIS_URL: redis://
    command: >
      sh -c "./post-backend.sh"
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      client:
        condition: service_healthy
    networks:
      - my_network

volumes:
  postgres_data:
  app:

networks:
  my_network:
    driver: bridge
