services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: cirs
      POSTGRES_PASSWORD: cirs_password
      POSTGRES_DB: cirs
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "cirs"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  client:
    image: node:7.8
    working_dir: /app
    volumes:
      - .:/app
    environment:
      DEBUG: ${DEBUG}
      BASE_URL: ${BASE_URL}
      PORT: ${PORT}
      REDIS_URL: ${REDIS_URL}
    command: >
      sh -c "rm -f /usr/local/bin/yarn /usr/local/bin/yarnpkg &&
             npm install -g yarn &&
             yarn &&
             yarn build:dev"
    healthcheck:
      test: ["CMD", "sh", "-c", "test -f /app/requirements.txt"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  backend:
    image: python:3.9
    working_dir: /app
    hostname: ${HOSTNAME}
    volumes:
        - .:/app
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DEBUG: ${DEBUG}
      BASE_URL: ${BASE_URL}
      PORT: ${PORT}
      REDIS_URL: ${REDIS_URL}
    command: >
      sh -c "chmod +x ./post-backend.sh && ./post-backend.sh"
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      client:
        condition: service_healthy

volumes:
  postgres_data:
  app: