#!/usr/bin/env python
import argparse

import file_io
import interpolate


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('voxels', help='Input path to read voxels-file')
    parser.add_argument('m_s', help='Input path to read rigidly registered pairs of points (M_s)')
    parser.add_argument('distortion', help='Output path to write distortion-file')
    args = parser.parse_args()

    voxel_data = file_io.load_voxels(args.voxels)
    m_s_data = file_io.load_m_s(args.m_s)

    TP_A_S = m_s_data['TP_A_S']
    TP_B = m_s_data['TP_B']

    ijk_to_xyz = voxel_data['ijk_to_patient_xyz_transform']
    ijk_shape = voxel_data['voxels'].shape

    distortion_grid = interpolate.interpolate_distortion(TP_A_S, TP_B, ijk_to_xyz, ijk_shape)

    file_io.save_distortion(args.distortion, {
        'distortion': distortion_grid,
    })
