#!/usr/bin/env python
import argparse

import scipy.io

import interpolate

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('voxels', help='Input path to read voxels mat-file')
    parser.add_argument('m_s', help='Input path to read rigidly registered pairs of points (M_s)')
    parser.add_argument('distortion', help='Output path to write distortion file')
    args = parser.parse_args()

    voxel_data = scipy.io.loadmat(args.voxels)
    m_s_data = scipy.io.loadmat(args.m_s)

    TP_A_S = m_s_data['TP_A_S']
    TP_B = m_s_data['TP_B']

    ijk_to_xyz = voxel_data['ijk_to_patient_xyz_transform']
    ijk_shape = voxel_data['voxels'].shape

    distortion_grid = interpolate.interpolate_distortion(TP_A_S, TP_B, ijk_to_xyz, ijk_shape)

    scipy.io.savemat(args.distortion, {
        'distortion': distortion_grid,
    }, do_compression=True)
