#!/usr/bin/env python
#
# Script to convert a mat file containing points into a 3D slicer "fiducial" file.
#
# See: https://www.slicer.org/wiki/Documentation/Nightly/Modules/Markups
# for details
import sys

import scipy.io


if __name__ == '__main__':
    if len(sys.argv) != 3:
        print('Usage: points2fcsv MATFILE CSVFILE')
        sys.exit(1)

    input_xyz_mat_filename = sys.argv[1]
    points = scipy.io.loadmat(input_xyz_mat_filename)['points']

    output_xyz_csv_filename = sys.argv[2]
    with open(output_xyz_csv_filename, 'w') as f:
        print('# Markups fiducial file version = 4.6', file=f)
        print('# CoordinateSystem = 1', file=f)  # 1 = LPS (Left, Posterior, Supine)
        print('# columns = id,x,y,z', file=f)  # there are many more possible columns for this
        for i, point in enumerate(points.T):
            print('{},{},{},{}'.format(i, point[0], point[1], point[2]), file=f)

