#!/usr/bin/env python
import argparse

import scipy.io

from registration import rigidly_register_and_categorize
import affine
import points_utils

import logging
log = logging.getLogger(__name__)


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('a', help='Input path to read A points mat-file')
    parser.add_argument('b', help='Input path to read B points mat-file')
    parser.add_argument('output', help='Output path to write all data to mat-file')
    args = parser.parse_args()

    A = scipy.io.loadmat(args.a)['points']
    B = scipy.io.loadmat(args.b)['points']

    xyztpx, FN_A_S, TP_A_S, TP_B, FP_B = rigidly_register_and_categorize(A, B)

    scipy.io.savemat(args.output, {
        'xyztpx': xyztpx,
        'FN_A_S': FN_A_S,
        'TP_A_S': TP_A_S,
        'TP_B': TP_B,
        'FP_B': FP_B,
    })
