#!/usr/bin/env python
import sys

import scipy.io

from registration import register


if __name__ == '__main__':
    if len(sys.argv) != 4:
        print('Usage: register AMAT BMAT FILE')
        sys.exit(1)

    A_xyz_mat_filename = sys.argv[1]
    A = scipy.io.loadmat(A_xyz_mat_filename)['points']

    B_xyz_mat_filename = sys.argv[2]
    B = scipy.io.loadmat(B_xyz_mat_filename)['points']

    x, y, z, theta, phi, xi = register(A, B)

    output_mat_filename = sys.argv[3]
    scipy.io.savemat(output_mat_filename, {
        'x': x,
        'y': y,
        'z': z,
        'theta': theta,
        'phi': phi,
        'xi': xi,
    })
