#!/usr/bin/env python
import sys

import scipy.io

from reports import generate_report


if __name__ == '__main__':
    if len(sys.argv) != 4:
        print('Usage: report A B REPORT')
        sys.exit(1)

    A_xyz_mat_filename = sys.argv[1]
    A = scipy.io.loadmat(A_xyz_mat_filename)['points']

    B_xyz_mat_filename = sys.argv[2]
    B = scipy.io.loadmat(B_xyz_mat_filename)['points']

    output_pdf_filename = sys.argv[3]
    generate_report(A, B, output_pdf_filename)
