#!/usr/bin/env python
import argparse

import scipy.io

from reports import generate_report


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('m_s', help='Input path to read rigidly registered pairs of points (M_s)')
    parser.add_argument('report', help='Output path to write NEMA report')
    args = parser.parse_args()

    m_s_data = scipy.io.loadmat(args.m_s)

    TP_A_S = m_s_data['TP_A_S']
    TP_B = m_s_data['TP_B']

    generate_report(TP_A_S, TP_B, args.report)
