#!/bin/bash
# Run one dataset against another dataset

set -e

output=$1
src=$2
golden=$3

mkoutput -p $output

./dicom2voxels $src $output/voxels.mat
./dicom2voxels $golden $output/golden-voxels.mat
./diffvoxels $output/voxels.mat $output/golden-voxels.mat $output/diff-voxels.mat

./feature_detection $output/voxels.mat $output/unregistered-points-raw.mat
cp $output/unregistered-points-raw.mat $output/golden-points.mat
./annotate $output/voxels.mat $output/golden-points.mat

./feature_detection $output/golden-voxels.mat $output/golden-unregistered-points.mat

./register $output/golden-points.mat $output/golden-unregistered-points.mat $output/matched-points.mat
./interpolate $output/golden-voxels.mat $output/matched-points.mat $output/golden-distortion.mat
./distortionstats $output/golden-distortion.mat
