#!/usr/bin/env python
import sys

import scipy.io
import matplotlib.pyplot as plt

from visualization import scatter3


if __name__ == '__main__':
    if len(sys.argv) < 2:
        print('Usage: scatter3 MATFILE [MATFILES...]')
        sys.exit(1)
    input_files = sys.argv[1:]

    label_to_points = {f: scipy.io.loadmat(f)['points'] for f in input_files}
    scatter3(label_to_points)

    plt.show()
