#!/usr/bin/env python
import sys
import itertools

import scipy.io
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D


colors = itertools.cycle(["r", "b", "g"])


if __name__ == '__main__':
    if len(sys.argv) < 2:
        print('Usage: scatter3 MATFILE [MATFILES...]')
        sys.exit(1)
    input_files = sys.argv[1:]
    fig = plt.figure(figsize=(10, 10))
    ax = fig.add_subplot(111, projection='3d')

    for c, f in zip(colors, input_files):
        points = scipy.io.loadmat(f)['points']
        ax.scatter(points[:, 0], points[:, 1], points[:, 2], color=c, label=f)

    ax.set_xlabel('x [mm]')
    ax.set_ylabel('y [mm]')
    ax.set_zlabel('z [mm]')
    plt.legend()
    plt.show()
