#!/usr/bin/env python
import argparse

import scipy.io
import matplotlib.pyplot as plt

from visualization import scatter3
from utils import split_file_variable_arg


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('points', nargs='+', default=None)
    args = parser.parse_args()

    label_to_points = {}
    for arg in args.points:
        path, variable = split_file_variable_arg(arg, 'points')
        label_to_points[arg] = scipy.io.loadmat(path)[variable]

    scatter3(label_to_points)

    plt.show()
