#!/usr/bin/env python
import argparse

import scipy.io
import matplotlib.pylab as plt
from slicer import Slicer


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('voxels')
    args = parser.parse_args()

    voxels = scipy.io.loadmat(args.voxels)['voxels']
    Slicer(voxels).draw()
    plt.show()
