#!/usr/bin/env python
import sys

import scipy.io
import matplotlib.pylab as plt
import slicer


if __name__ == '__main__':
    if len(sys.argv) <= 1:
        print('Usage: slice_viewer VOXELS_MATFILE')
        sys.exit(1)

    input_data = scipy.io.loadmat(sys.argv[1])
    voxels = input_data['voxels']

    slicer.Slicer(voxels)
    plt.show()
