#!/usr/bin/env python
import argparse

import scipy.io
import matplotlib.pylab as plt
from slicer import Slicer, render_slices, render_cursor


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('voxels')
    args = parser.parse_args()

    voxels = scipy.io.loadmat(args.voxels)['voxels']
    slicer = Slicer(voxels)
    slicer.add_renderer(render_slices)
    slicer.add_renderer(render_cursor)
    slicer.draw()
    plt.show()
