#!/usr/bin/env python
import argparse

import numpy as np

import file_io
import affine


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('voxels')
    parser.add_argument('points')
    args = parser.parse_args()

    points_transposed = file_io.load_points(args.points)['points']
    ijk_to_xyz = file_io.load_voxels(args.voxels)['ijk_to_patient_xyz_transform']
    xyz_to_ijk = np.linalg.inv(ijk_to_xyz)
    points_jik = affine.apply_affine(xyz_to_ijk, points_transposed)
    points_ijk = points_jik.copy()
    points_ijk[0, :] = points_jik[1, :]
    points_ijk[1, :] = points_jik[0, :]
    points = affine.apply_affine(ijk_to_xyz, points_ijk)

    file_io.save_points(args.points, {
        'points': points,
    })
