#!/bin/bash
distorted_voxels="tmp/mri-001-axial-voxel-decimated-$1.mat"
distorted_points="tmp/mri-001-axial-points-decimated-$1.mat"
image="tmp/mri-001-axial-points-decimated-$1.png"
echo $distorted_voxels $distorted_points $undistorted_points
python -m testing.decimate_slices tmp/mri-001-axial-voxels.mat tmp/mri-001-axial-voxel-decimated-$1.mat $1
echo DETECTING POINTS
./detect_features $distorted_voxels $distorted_points
echo COMPARING POINTS $1
python -m testing.calculate_metrics data/points/mri-001-axial-golden.mat $distorted_points
echo GENERATING PLOT $1
./overlaypoints tmp/mri-001-axial-voxels.mat data/points/mri-001-axial-golden.mat $distorted_points --distorted_voxels $distorted_voxels --distorted_points $distorted_points --save $image
