export const UPDATE_SCAN = 'UPDATE_SCAN';
export const POLL_SCANS_FAILURE = 'POLL_SCANS_FAILURE';
export const UPDATE_TOLERANCE = 'UPDATE_TOLERANCE';
export const UPDATE_TOLERANCE_SUCCESS = 'UPDATE_TOLERANCE_SUCCESS';
export const FILTER_SCANS = 'FILTER_SCANS';
