#!/usr/bin/env python
import argparse
import re

import dicom


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('dicom_filename', help='A valid DICOM file')
    parser.add_argument('tag_names', nargs='*', metavar='<tag>', help='DICOM tag names to print; if blank, print all tags')
    args = parser.parse_args()

    dicom_dataset = dicom.read_file(args.dicom_filename)

    if not args.tag_names:
        for name, value in dicom_dataset.items():
            print(name)
            print(value)
    else:
        for name in args.tag_names:
            if getattr(dicom_dataset, name, None):
                print(name)
                print(getattr(dicom_dataset, name))
            else:
                print('Tag "{}" does not exist'.format(name))
