#!/usr/bin/env python
#
# Script to convert a CSV file with three columns (x, y, z) of points
# into a points file
import argparse

import numpy as np

import process.file_io


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('csvfile', help='Input path to read csv-file')
    parser.add_argument('pointsfile', help='Output path to write points-file')
    args = parser.parse_args()

    points = np.genfromtxt(args.csvfile)
    process.file_io.save_points(args.pointsfile, {
        'points': points.T,
    })
