#!/usr/bin/env python
import argparse

from process import file_io
from process.feature_detection import FeatureDetector
if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('voxels', help='Input path to read voxels-file')
    parser.add_argument('points', help='Output path to write points-file')
    args = parser.parse_args()

    voxel_data = file_io.load_voxels(args.voxels)
    voxels = voxel_data['voxels']
    ijk_to_xyz = voxel_data['ijk_to_patient_xyz_transform']
    phantom_name = voxel_data['phantom_name']
    modality = voxel_data['modality']

    points_in_patient_xyz, false_positives_points_xyz = FeatureDetector(phantom_name, modality, voxels, ijk_to_xyz).run(return_false_positives=True)
    file_io.save_points(args.points, {'points': points_in_patient_xyz})
