#!/usr/bin/env python
#
# Script to convert a points file to a  CSV file with three columns (x, y, z)
import argparse

import numpy as np

import process.file_io


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('pointsfile', help='Input path to write points-file')
    parser.add_argument('csvfile', help='Output path to read csv-file')
    args = parser.parse_args()

    points = process.file_io.load_points(args.pointsfile)['points']
    np.savetxt(args.csvfile, points.T, delimiter=',')
