#!/usr/bin/env python
import argparse
import subprocess

from process import file_io, phantoms

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('voxels', help='Input path to read voxels-file')
    parser.add_argument('b', help='Input path to read B points-file')
    parser.add_argument('output', help='Output path to write m_s-file')
    args = parser.parse_args()

    phantom_name = file_io.load_voxels(args.voxels)['phantom_name']
    a_file = phantoms.paramaters[phantom_name]['points_file']

    cmd = ['./register', a_file, args.b, args.output]
    print(' '.join(cmd))
    subprocess.run(cmd, check=True)
