#!/usr/bin/env python
import argparse

from process import file_io
from registration import rigidly_register_and_categorize

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('a', help='Input path to read A points-file')
    parser.add_argument('b', help='Input path to read B points-file')
    parser.add_argument('output', help='Output path to write m_s-file')
    args = parser.parse_args()

    A = file_io.load_points(args.a)['points']
    B = file_io.load_points(args.b)['points']

    # TODO: think through how we would calculate the isocenter; without doing
    # this, the invocation to `rigidly_register_and_categorize` will fail
    xyztpx, FN_A_S, TP_A_S, TP_B, FP_B = rigidly_register_and_categorize(A, B)

    file_io.save_m_s(args.output, {
        'xyztpx': xyztpx,
        'FN_A_S': FN_A_S,
        'TP_A_S': TP_A_S,
        'TP_B': TP_B,
        'FP_B': FP_B,
    })
