#!/usr/bin/env python
#
# Script to convert a matlab file containing voxels and an affine matrix into a
# *.nii file
import argparse

import nibabel as nib

from process import file_io

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('voxels', help='Input path to read voxels-file')
    parser.add_argument('nii', help='Output path to write nii-file')
    args = parser.parse_args()

    voxels_data = file_io.load_voxels(args.voxels)

    nii_data = nib.Nifti1Image(voxels_data['voxels'], voxels_data['ijk_to_xyz'])
    nib.save(nii_data, args.nii)
