# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-02 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='errors',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='scan',
            name='processing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scan',
            name='result',
            field=models.TextField(null=True),
        ),
    ]
