# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20170320_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='goldenfiducials',
            name='source_type',
            field=models.CharField(choices=[('CT', 'CT'), ('CAD', 'CAD')], default='CAD', help_text='The source type for the golden fiducials  (e.g. CT Scan or CAD Model).', max_length=3),
            preserve_default=False,
        ),
    ]
