# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_goldenfiducials_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='goldenfiducials',
            name='is_active',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goldenfiducials',
            name='source_type',
            field=models.CharField(choices=[('CT', 'CT Scan'), ('CAD', 'CAD Model'), ('Raw', 'Raw Points')], help_text='The source type for the golden fiducials  (e.g. CT Scan or CAD Model).', max_length=3),
        ),
    ]
