# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 16:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import server.django_numpy.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20170321_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False, help_text='Deleted items are hidden from non-admins')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified_on', models.DateTimeField(auto_now=True)),
                ('mat_file', models.FileField(upload_to='cad_model/mat_file')),
                ('voxels', server.django_numpy.fields.NumpyTextField()),
                ('ijk_to_xyz', server.django_numpy.fields.NumpyTextField()),
                ('shape', server.django_numpy.fields.NumpyTextField()),
            ],
            options={
                'verbose_name': 'CAD Model',
            },
        ),
        migrations.CreateModel(
            name='PhantomModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False, help_text='Deleted items are hidden from non-admins')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='This is how the phantom model will be identified within the UI', max_length=255)),
                ('model_number', models.CharField(help_text='The model number (e.g. 603A)', max_length=255)),
                ('cad_model', models.ForeignKey(help_text='The hard-coded gold standard points for the phantom model', null=True, on_delete=django.db.models.deletion.CASCADE, to='common.CadModel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='goldenfiducials',
            name='source_type',
            field=models.CharField(choices=[('CT', 'CT Scan'), ('CAD', 'CAD Model'), ('RAW', 'Raw Points')], help_text='The source type for the golden fiducials  (e.g. CT Scan or CAD Model).', max_length=3),
        ),
        migrations.AlterField(
            model_name='phantom',
            name='model',
            field=models.ForeignKey(help_text='The model of phantom (e.g. the CIRS 603A head phantom)', on_delete=django.db.models.deletion.CASCADE, to='common.PhantomModel'),
        ),
        migrations.AddField(
            model_name='goldenfiducials',
            name='cad_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.CadModel'),
        ),
    ]
