# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 20:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20170321_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhantomModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False, help_text='Deleted items are hidden from non-admins')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='This is how the phantom model will be identified within the UI', max_length=255)),
                ('model_number', models.CharField(help_text='The model number (e.g. 603A)', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='goldenfiducials',
            name='source_type',
        ),
        migrations.AddField(
            model_name='goldenfiducials',
            name='type',
            field=models.CharField(choices=[('CAD', 'CAD Model'), ('CT', 'CT Scan'), ('RAW', 'Raw Points')], default='CT', help_text='The source type for the golden fiducials  (e.g. CT Scan or CAD Model).', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='phantom',
            name='model',
            field=models.ForeignKey(help_text='The model of phantom (e.g. the CIRS 603A head phantom)', on_delete=django.db.models.deletion.CASCADE, to='common.PhantomModel'),
        ),
    ]
