# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_auto_20170323_1953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='global',
            options={'managed': False, 'permissions': (('configuration', 'ConfigurationView'), ('manage_users', 'Manage Users'))},
        ),
        migrations.AlterField(
            model_name='goldenfiducials',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
