# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 20:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_auto_20170328_1854'),
        ('common', '0010_auto_20170327_2006'),
    ]

    operations = [
    ]
