# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 17:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_merge_20170328_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldenfiducials',
            name='type',
            field=models.CharField(choices=[('CAD', 'CAD Model'), ('CT', 'CT Scan'), ('CSV', 'CSV Points')], help_text='The source type for the golden fiducials  (e.g. CT Scan or CAD Model).', max_length=3),
        ),
        migrations.AlterField(
            model_name='phantom',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Institution'),
        ),
    ]
