# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 20:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_auto_20170329_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='scan',
            name='detected_fiducials',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Fiducials'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='tolerance',
            field=models.FloatField(null=True),
        ),
    ]
