# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 22:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_auto_20170404_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='distortion',
        ),
        migrations.AddField(
            model_name='scan',
            name='TP_A_S',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scan_tp_a_s_set', to='common.Fiducials'),
        ),
        migrations.AddField(
            model_name='scan',
            name='TP_B',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scan_tp_b_set', to='common.Fiducials'),
        ),
        migrations.AddField(
            model_name='scan',
            name='executive_report',
            field=models.FileField(null=True, upload_to='scan/executive_report'),
        ),
        migrations.AddField(
            model_name='scan',
            name='full_report',
            field=models.FileField(null=True, upload_to='scan/full_report'),
        ),
    ]
