# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_auto_20170424_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicomseries',
            name='frame_of_reference_uid',
            field=models.CharField(default='1.1.1.1', help_text='The DICOM Series Instance UID, which should uniquely identify a scan', max_length=64, verbose_name='Frame Of Reference UID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dicomseries',
            name='patient_id',
            field=models.CharField(default='1.1.1.1', help_text='The DICOM Series Instance UID, which should uniquely identify a scan', max_length=64, verbose_name='Patient ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dicomseries',
            name='study_uid',
            field=models.CharField(default='1.1.1.1', help_text='The DICOM Series Instance UID, which should uniquely identify a scan', max_length=64, verbose_name='Study Instance UID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scan',
            name='processing',
            field=models.BooleanField(default=True),
        ),
    ]
