# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_auto_20170504_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='raw_data',
            field=models.FileField(null=True, upload_to='scan/raw_data'),
        ),
    ]
