# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 19:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_scan_raw_data'),
        ('common', '0018_auto_20170516_1640'),
    ]

    operations = [
    ]
