# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 07:19
from __future__ import unicode_literals

from django.db import migrations
import server.django_numpy.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0020_auto_20170524_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicomseries',
            name='voxels',
            field=server.django_numpy.fields.NdarrayFileField(upload_to='dicom_series/voxels'),
        ),
        migrations.AlterField(
            model_name='fiducials',
            name='fiducials',
            field=server.django_numpy.fields.NdarrayFileField(upload_to='fiducials/fiducials'),
        ),
    ]
