# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-10 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0022_auto_20170608_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicomseries',
            name='frame_of_reference_uid',
            field=models.CharField(blank=True, help_text='The DICOM Series Instance UID, which should uniquely identify a scan', max_length=64, null=True, verbose_name='Frame Of Reference UID'),
        ),
    ]
