# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-10 17:09
from __future__ import unicode_literals

from django.db import migrations
import server.django_numpy.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0023_auto_20170610_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicomseries',
            name='voxels',
            field=server.django_numpy.fields.NdarrayTextField(),
        ),
        migrations.AlterField(
            model_name='fiducials',
            name='fiducials',
            field=server.django_numpy.fields.NdarrayTextField(),
        ),
    ]
