# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-22 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0025_auto_20170620_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequence',
            name='tolerance',
            field=models.FloatField(default=3, help_text='The default maximum allowable distortion (mm) for new machine-sequence pairs that use this sequence. The tolerance for a machine-sequence pair can be customized after the first scan is uploaded.'),
        ),
    ]
