# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-28 18:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0026_auto_20170622_1502'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scan',
            options={'ordering': ('-dicom_series__acquisition_date', '-created_on')},
        ),
    ]
