# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0028_auto_20170726_0619'),
    ]

    operations = [
        migrations.AddField(
            model_name='goldenfiducials',
            name='filename',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
