# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-21 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0029_goldenfiducials_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicomseries',
            name='acquisition_date',
            field=models.DateField(help_text='The DICOM Series Instance Acquisition Date', null=True),
        ),
    ]
