# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-11 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0030_auto_20171221_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='license_expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='scans_remaining',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
