# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-29 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0034_auto_20180214_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicomseries',
            name='columns',
            field=models.PositiveSmallIntegerField(help_text='Number of columns in the image', null=True),
        ),
        migrations.AddField(
            model_name='dicomseries',
            name='modality',
            field=models.CharField(choices=[('MR', 'Magnetic Resonance'), ('CT', 'Computed Tomography'), ('SC', 'Secondary Capture')], help_text='The DICOM Modality', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='dicomseries',
            name='number_of_slices',
            field=models.PositiveSmallIntegerField(help_text='Number of slices in the image', null=True),
        ),
        migrations.AddField(
            model_name='dicomseries',
            name='patient_birth_date',
            field=models.DateField(help_text="The Patient's Date of Birth", null=True),
        ),
        migrations.AddField(
            model_name='dicomseries',
            name='patient_name',
            field=models.CharField(help_text="The Patient's Name", max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='dicomseries',
            name='patient_sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], help_text="The Patient's Sex", max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='dicomseries',
            name='rows',
            field=models.PositiveSmallIntegerField(help_text='Number of rows in the image', null=True),
        ),
        migrations.AlterField(
            model_name='dicomseries',
            name='patient_id',
            field=models.CharField(help_text="The Patient's ID", max_length=64, null=True, verbose_name='Patient ID'),
        ),
        migrations.AlterField(
            model_name='dicomseries',
            name='study_uid',
            field=models.CharField(help_text='The DICOM Study Instance UID', max_length=64, verbose_name='Study Instance UID'),
        ),
    ]
