# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-20 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0037_purchaseorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='number',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
