name: Build and Deploy to Azure

on:
  push:
    branches:
      - docker-prep

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Azure Container Registry (ACR)
      uses: docker/login-action@v2
      with:
        registry: distortioncheckacr.azurecr.io
        username: ${{ secrets.AZURE_CLIENT_ID }}
        password: ${{ secrets.AZURE_CLIENT_SECRET }}

    - name: Build and push Docker image to ACR
      run: |
        docker build -t distortioncheckacr.azurecr.io/distortion_check:latest .
        docker push distortioncheckacr.azurecr.io/distortion_check:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure App Service
      run: |
        az containerapp up \
          --name distortioncheck-container \
          --resource-group distortioncheck_group \
          --location eastus \
          --environment 'my-container-apps' \
          --image distortioncheckacr.azurecr.io/distortion_check:latest \
          --target-port 8000 \
          --ingress external \
          --query properties.configuration.ingress.fqdn
