name: Build and Deploy to Azure

on:
  push:
    branches:
      - docker-prep

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/distortion_check:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/distortion_check:latest

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure App Service
      run: |
        az containerapp up \
          --name distortioncheck-container \
          --resource-group distortioncheck_group \
          --location eastus \
          --environment 'my-container-apps' \
          --image ${{ secrets.DOCKER_USERNAME }}/distortion_check:latest \
          --target-port 8000 \
          --ingress external \
          --query properties.configuration.ingress.fqdn
